// Generated by scripts/generate-node-distribution.ts from runtime/runtime-manifest.json.
// Do not edit manually; run pnpm runtime:node:generate after a Node version bump.
// These literals are the reviewed outbound-download boundary for CodeQL.

export const nodeRelease = {
  version: "24.19.0",
  directory: "v24.19.0",
  distributions: {
    "win32-x64": { file: "node-v24.19.0-win-x64.zip", bin: "node-v24.19.0-win-x64/node.exe" },
    "win32-arm64": { file: "node-v24.19.0-win-arm64.zip", bin: "node-v24.19.0-win-arm64/node.exe" },
    "darwin-arm64": { file: "node-v24.19.0-darwin-arm64.tar.gz", bin: "node-v24.19.0-darwin-arm64/bin/node" },
    "darwin-x64": { file: "node-v24.19.0-darwin-x64.tar.gz", bin: "node-v24.19.0-darwin-x64/bin/node" },
    "linux-x64": { file: "node-v24.19.0-linux-x64.tar.xz", bin: "node-v24.19.0-linux-x64/bin/node" },
    "linux-arm64": { file: "node-v24.19.0-linux-arm64.tar.xz", bin: "node-v24.19.0-linux-arm64/bin/node" },
  },
} as const;
