// Generate the static Node release data used by download-node.ts.
//
// The runtime manifest stays the single source of truth. This generated file
// is deliberately source-code literals: CodeQL can then prove that the
// outbound request cannot carry arbitrary file contents. `--check` is used
// by release preflight to reject a stale generated file.

import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { fail, ok, readManifest, repoRoot } from "./lib/common.ts";

const VERSION_RE = /^(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)$/;
const outputPath = join(repoRoot, "scripts", "lib", "node-distribution.ts");

function render(version: string): string {
  const base = `node-v${version}`;
  const distributions = [
    ["win32-x64", `${base}-win-x64.zip`, `${base}-win-x64/node.exe`],
    ["win32-arm64", `${base}-win-arm64.zip`, `${base}-win-arm64/node.exe`],
    ["darwin-arm64", `${base}-darwin-arm64.tar.gz`, `${base}-darwin-arm64/bin/node`],
    ["darwin-x64", `${base}-darwin-x64.tar.gz`, `${base}-darwin-x64/bin/node`],
    ["linux-x64", `${base}-linux-x64.tar.xz`, `${base}-linux-x64/bin/node`],
    ["linux-arm64", `${base}-linux-arm64.tar.xz`, `${base}-linux-arm64/bin/node`],
  ] as const;

  return [
    "// Generated by scripts/generate-node-distribution.ts from runtime/runtime-manifest.json.",
    "// Do not edit manually; run pnpm runtime:node:generate after a Node version bump.",
    "// These literals are the reviewed outbound-download boundary for CodeQL.",
    "",
    "export const nodeRelease = {",
    `  version: ${JSON.stringify(version)},`,
    `  directory: ${JSON.stringify(`v${version}`)},`,
    "  distributions: {",
    ...distributions.map(
      ([platform, file, bin]) =>
        `    ${JSON.stringify(platform)}: { file: ${JSON.stringify(file)}, bin: ${JSON.stringify(bin)} },`,
    ),
    "  },",
    "} as const;",
    "",
  ].join("\n");
}

const version = readManifest().nodeVersion;
if (!VERSION_RE.test(version)) {
  fail(`runtime-manifest.json nodeVersion ${JSON.stringify(version)} is not a semver triple`);
}
const expected = render(version);

if (process.argv.includes("--check")) {
  let actual: string;
  try {
    actual = readFileSync(outputPath, "utf8");
  } catch (error) {
    fail(`could not read generated node distribution: ${(error as Error).message}`);
  }
  if (actual !== expected) {
    fail("generated node distribution is stale; run pnpm runtime:node:generate and commit the result");
  }
  ok(`generated node distribution aligned: ${version}`);
} else {
  writeFileSync(outputPath, expected);
  ok(`generated node distribution: ${version}`);
}
